### ISSUE TITLE
Establish a GitHub organization for Boilr

### ISSUE THREAD

**Issue by philoserf** [Ilyes512/boilr#26]
Such an organization could host the boiler and community managed/submitted template repositories. 

This could remove dependency upon templates currently referenced in the wiki documents.

**Comment by Ilyes512** [comment]
I dont mind, BUT I either want a okey from the original creator OR, I want to (re)create a new package under a new name from scratch (this is also to get some more work experience with golang and to have a far better intimate knowledge of the code base). Ofcourse a reference to the original project will still be included, but there wil be no direct copy/paste of the code.

**Comment by philoserf** [comment]
ACK. I investigated boilr and others over a year ago. The impulse to build fresh with new experience is shared.
